In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [5]:
df = pd.read_csv('../data/processed/casas.csv')

In [6]:
df.head()

   tamanho   ano  garagem   preco
0    159.0  2003        2  208500
1    117.0  1976        2  181500
2    166.0  2001        2  223500
3    160.0  1915        3  140000
4    204.0  2000        3  250000

In [7]:
X = df.drop('preco', axis=1)
y = df['preco']

In [8]:
X.head()

   tamanho   ano  garagem
0    159.0  2003        2
1    117.0  1976        2
2    166.0  2001        2
3    160.0  1915        3
4    204.0  2000        3

In [9]:
X_trian, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Linear Regression

In [10]:
import mlflow

In [11]:
mlflow.set_experiment('house-prices-eda')

<Experiment: artifact_location='file:///c:/Users/Paulo/Documents/mlflow-alura/notebooks/mlruns/400848448657434686', creation_time=1736728812844, experiment_id='400848448657434686', last_update_time=1736728812844, lifecycle_stage='active', name='house-prices-eda', tags={}>

In [12]:
mlflow.start_run()

In [13]:
from sklearn.linear_model import LinearRegression
import math

lr = LinearRegression()
lr.fit(X_trian, y_train)

LinearRegression()

In [12]:
mlflow.sklearn.log_model(lr,'lr')

2025/01/13 18:52:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

PermissionError: [Errno 13] Permission denied: '/c:'

In [13]:
from sklearn.metrics import mean_squared_error, r2_score

In [14]:
mse = mean_squared_error(y_test, lr.predict(X_test))

In [15]:
mse

2078666917.928992

In [14]:
from xgboost import XGBRFRegressor
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression

# Generate synthetic data
X, y = make_regression(n_samples=100, n_features=20, noise=0.1, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fit the model
xgb = XGBRFRegressor(random_state=42)
xgb.fit(X_train, y_train)

XGBRFRegressor(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bytree=None, device=None,
               early_stopping_rounds=None, enable_categorical=False,
               eval_metric=None, feature_types=None, gamma=None,
               grow_policy=None, importance_type=None,
               interaction_constraints=None, max_bin=None,
               max_cat_threshold=None, max_cat_to_onehot=None,
               max_delta_step=None, max_depth=None, max_leaves=None,
               min_child_weight=None, missing=nan, monotone_constraints=None,
               multi_strategy=None, n_estimators=None, n_jobs=None,
               num_parallel_tree=None, objective='reg:squarederror',
               random_state=42, reg_alpha=None, ...)